### ISSUE TITLE
configurable parameters in constant.py

### ISSUE THREAD

**Issue by Zongshun96** [dmpalyvos/debs-2020-challenge#1]
Hi, 
    I was wonderring if your are going to change the INPUT_BATCH_SIZE parameter in the constant.py in real evaluation? Can we assume the number of records in each batch of data sent with a single GET request is always 1000? (Can we assume the INPUT_BATCH_SIZE to be 1000 always?)

Thanks,
Zongshun Zhang

**Comment by dmpalyvos** [comment]
Yes, the batch size will always be 1000 for query 1. For the second query it can be less, as described in the challenge call.
